### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by ghost** [brendanfh/onyx#25]
@brendanfh 

Hi, I am very interested in Onyx Programming Language, I love this syntax.

I have a few questions about it:

**1.** Where can I find stdio library for Onyx with `printf`, `fprintf` `sprintf`,`scanf` and etc.

**2.** How to read input? (like in C `scanf`?)

**3.** How to declare namespaces?

**4.** Where can I find documentation for it?

**5.** How to use `for`/`repeat` loop in Onyx?

**6.** Is there something like `#ifdef` meta directive?

**7.** What about catching exceptions in Onyx? (`try-catch`?)

**Comment by brendanfh** [comment]
Hi, I'm glad you're interested in the language! This kind of syntax is definitely one of my favorites too.

As to your questions, I am still working on a standard library of any kind in the language. Most of what is there in the `core` folder is just what I have needed for testing the language. There are some useful things such as a very basic printf implementation but nothing super thought out or put together.

Currently, there are not "namespaces" in the traditional sense in the language. To split up your code, you mark a package as part of a specific *package* by saying ```package foo``` as the first line in a file. Then, all declarations not marked `#private` or `#private_file` will be part of that package. To use them from another package, refer to the current version of the README that explains how to use packages.

Since this has just been a hobby project I have not kept very careful documentation of the language features as I have been going. I have started to write a basic spec for it but currently there is no source of documentation. The `examples`, `progs`, `tests` and `core` folders contain most of what is written in the language at the moment.

A `for` loop works with the following syntax:
```
for variable: iterable { ... }
```
`variable` is the symbol to bind the current iteration value. `iterable` is some expression that currently has to result in something of a specific type that can be iterated over. Currently, those types are `range`, `[N] T`, `[] T`, `[..] T`. Basically, anything of with an array-like type, or a `range` which can be written using `low .. high`. When iterating over array-like types, iteration is done by value. If you instead want to do it by pointer, place a `^` in front of `variable`:
```
for ^variable: array_like_iterable { ... }
```

I have not implemented any kind of compile-time conditionals yet, but they are on my to-do list.

I have thought about exceptions and I came to the conclusion that most programs don't need them. Instead of adding additional features to the language to handle this kind of logic, I think its easier for both the language developer and the language users to use the features already in the language to achieve this. Take this example:
```
file_open :: proc (file: ^File, path: string) -> FileError { ... }

main :: proc (args: [] cstring) {
    file: File;
    if err := file_open(^file, "foo.txt"); err != FileError.Success {
        // handle the error properly
    }
}
```
By using the features already in the language, something very similar to a try-catch can be achieve, without adding any additional complexity.

I will be working on more examples, proper documentation, and how to set up Onyx on different systems very soon.
